// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwguEzBKzm3RQsfoKuZ-LQOh3pcLxqQiE',
    appId: '1:331997448598:web:fc110136695a681d3a35b7',
    messagingSenderId: '331997448598',
    projectId: 'studyplanner-4f0a9',
    authDomain: 'studyplanner-4f0a9.firebaseapp.com',
    storageBucket: 'studyplanner-4f0a9.firebasestorage.app',
    measurementId: 'G-09NS2TMLCX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjBBpHI__nsyfTJqqEiJ4bKFE3usbWvL8',
    appId: '1:331997448598:android:2a2fb35d387557aa3a35b7',
    messagingSenderId: '331997448598',
    projectId: 'studyplanner-4f0a9',
    storageBucket: 'studyplanner-4f0a9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9uWITF104ZfKWQAcLVx5Yph6zM3f7tgU',
    appId: '1:331997448598:ios:70892ca1cb6923ef3a35b7',
    messagingSenderId: '331997448598',
    projectId: 'studyplanner-4f0a9',
    storageBucket: 'studyplanner-4f0a9.firebasestorage.app',
    iosBundleId: 'com.example.project1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9uWITF104ZfKWQAcLVx5Yph6zM3f7tgU',
    appId: '1:331997448598:ios:70892ca1cb6923ef3a35b7',
    messagingSenderId: '331997448598',
    projectId: 'studyplanner-4f0a9',
    storageBucket: 'studyplanner-4f0a9.firebasestorage.app',
    iosBundleId: 'com.example.project1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDwguEzBKzm3RQsfoKuZ-LQOh3pcLxqQiE',
    appId: '1:331997448598:web:afdc7f7b519bc3343a35b7',
    messagingSenderId: '331997448598',
    projectId: 'studyplanner-4f0a9',
    authDomain: 'studyplanner-4f0a9.firebaseapp.com',
    storageBucket: 'studyplanner-4f0a9.firebasestorage.app',
    measurementId: 'G-29RYRTL27V',
  );
}
